### ISSUE TITLE
Paper draft

### ISSUE THREAD

**Issue by keli-ch** [nennigb/matchingep#1]
Hi Benoit, 

This repos is very interesting.  is it possible for you to send me the preview version of your paper ? I want to have a deep read on it. 
Thanks a lot.

Ke

**Comment by nennigb** [comment]
The paper has now been accepted for publication and would be online in open acces on  Wednesday 21 December 2022  (https://royalsocietypublishing.org/journal/rspa).

**Comment by nennigb** [comment]
The direct link is : https://royalsocietypublishing.org/doi/10.1098/rspa.2022.0484
